### ISSUE TITLE
[FEAT] iOS 3차 과제

### ISSUE THREAD

**Issue by yujinnee** [29th-WE-SOPT-iOS-Part/LeeYuJin#5]
## 📌 Feature Issue

3주차 과제는 TableView와 CollectionView를 활용하여 Youtube 홈 화면을 구성해보는 것입니다!
## 📝 To-do

▶️ Cell 구성하기

- [ ]  Xib파일로 TableView Cell 만들기
- [ ]  CollectionView Cell 만들기
- [ ]  확인 화면 UI 구성하기

▶️ 기능 구현 하기

- [ ]  UIView 구현하기
- [ ]  TableView 구현하기
- [ ]  CollectionView 구현하기

🔥도전과제

- [ ]  텍스트길이에 따라 크기가 다른 cell 구현하기
