### ISSUE TITLE
[FEAT] iOS 4차 과제

### ISSUE THREAD

**Issue by yujinnee** [29th-WE-SOPT-iOS-Part/LeeYuJin#8]
## 📌 Feature Issue

4주차 과제는 로그인, 회원가입에 실제 API를 붙여보는 과제입니다!
## 📝 To-do

▶️ 화면전환 구현하기

- [x]  시작 스토리보드 변경
- [ ]  프로필 눌렀을 때 로그인 화면으로 이동
- [x]  확인 화면 UI 구성하기

▶️ 서버 연결하기

- [x]  로그인 화면  - 서버에서 넘겨주는 메세지로 alert 띄우기
- [x]  회원가입 화면 - 서버에서 넘겨주는 메세지로 alert 띄우기 

🔥도전과제

- [ ]  로그인 할 때 받는 결과값 중 name 값 User Defaults에 저장한 뒤 화면에 이름 띄울 때 사용하기
